// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzuwuvjhqzijcpgleddt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6dXd1dmpocXppamNwZ2xlZGR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMTk4NjcsImV4cCI6MjA2NDc5NTg2N30.IbpRw5nRlApliNTl9YdPmx19evGExPhqZcA-_mr7Oqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);